import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiReact,
  SiGraphql,
  SiTypescript,
  SiFirebase,
  SiHeroku,
  SiRedux,
  SiNetlify,
  SiGit,
  SiGithub,
  SiStyledcomponents,
  SiAuth0,
  SiFacebook,
  SiGoogle,
  SiInstagram,
  SiTailwindcss,
  SiBootstrap,
  SiVercel,
  SiSupabase,
  SiNextdotjs,
  SiNuxt,
  SiVuedotjs,
  SiMui,
} from "react-icons/si";
import { FaLinkedin } from "react-icons/fa";
import type { IconType } from "react-icons";

export const iconMap: Record<string, IconType> = {
  SiHtml5,
  SiCss3: SiCss,
  SiCss,
  SiJavascript,
  SiReact,
  SiGraphql,
  SiTypescript,
  SiFirebase,
  SiHeroku,
  SiNextdotjs,
  SiNuxtdotjs: SiNuxt,
  SiNuxt,
  SiVuedotjs,
  SiRedux,
  SiMui,
  SiNetlify,
  SiGit,
  SiGithub,
  SiStyledcomponents,
  SiAuth0,
  SiLinkedin: FaLinkedin,
  SiFacebook,
  SiGoogle,
  SiInstagram,
  SiTailwindcss,
  SiBootstrap,
  SiVercel,
  SiSupabase,
};
